# Generated by Django 6.0.5 on 2026-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0', max_length=20, verbose_name='Teléfono / WhatsApp'),
            preserve_default=False,
        ),
    ]
