# Generated by Django 6.0.5 on 2026-05-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_size_alter_product_stock_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='imagen adicional')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen adicional',
                'verbose_name_plural': 'imágenes adicionales',
            },
        ),
    ]
